# Copyright @ 2023 - 2024, R3E Network
# All Rights Reserved

[workspace]
resolver = "2"


members = [
    "r3e",
    "r3e-api",
    "r3e-built-in-services",
    "r3e-config",
    "r3e-core",
    "r3e-deno",
    "r3e-event",
    # "r3e-js",
    "r3e-neo-services",
    "r3e-oracle",
    "r3e-proc-macros",
    "r3e-runlog",
    "r3e-runtime",
    "r3e-scheduler",
    "r3e-secrets",
    "r3e-stock",
    "r3e-store",
    "r3e-tee",
    "r3e-worker",
    "r3e-zk",
    "r3e-fhe",
]


[profile.release]
lto           = "fat"
opt-level     = 3
codegen-units = 1

# RUSTFLAGS = "-C target-cpu=native"
