version: '3.8'

services:
  r3e-faas-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - R3E_FAAS__GENERAL__ENVIRONMENT=development
      - R3E_FAAS__LOGGING__LEVEL=debug
      - RUST_BACKTRACE=1
    networks:
      - r3e-network
    tty: true
    stdin_open: true
    command: /bin/bash

networks:
  r3e-network:
    driver: bridge
