version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - R3E_FAAS__GENERAL__ENVIRONMENT=development
      - R3E_FAAS__LOGGING__LEVEL=debug
      - R3E_FAAS__STORAGE__PATH=/app/data
    volumes:
      - ./data/api:/app/data
    networks:
      - r3e-network
    depends_on:
      - worker

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    environment:
      - R3E_FAAS__GENERAL__ENVIRONMENT=development
      - R3E_FAAS__LOGGING__LEVEL=debug
      - R3E_FAAS__STORAGE__PATH=/app/data
    volumes:
      - ./data/worker:/app/data
    networks:
      - r3e-network

  # Development environment with all dependencies
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - .:/app
      - ./data/dev:/app/data
    environment:
      - R3E_FAAS__GENERAL__ENVIRONMENT=development
      - R3E_FAAS__LOGGING__LEVEL=debug
      - RUST_BACKTRACE=1
    networks:
      - r3e-network
    command: /bin/bash

networks:
  r3e-network:
    driver: bridge

volumes:
  data:
