# Copyright @ 2023 - 2024, R3E Network
# All Rights Reserved

[package]
name = "r3e-runtime"
version = "0.1.0"
edition = "2021"


[dependencies]
r3e-core  = { path = "../r3e-core" }

v8        =  { version = "0.91"    }
serde_v8  =  { version = "0.187"   }
serde     =  { version = "1", features = ["derive"] }

thiserror =  { version = "1" }


[dev-dependencies]
deno_core =  { version = "0.278.0" }
