apiVersion: v1
kind: ConfigMap
metadata:
  name: r3e-config
  namespace: r3e-faas
data:
  # Database connection string will be provided via environment variables
  # to avoid storing sensitive information in ConfigMaps
  redis_url: "redis://redis:6379/0"
  neo_rpc_url: "http://neo-node:10332"
  ethereum_rpc_url: "http://ethereum-node:8545"
  log_level: "info"
  storage_type: "rocksdb"
  max_concurrent_functions: "10"
  function_timeout_seconds: "30"
  api_port: "8080"
  worker_port: "8081"
