apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: r3e-faas
type: Opaque
data:
  # This is a placeholder that should be replaced with a secure password during deployment
  # The actual password should be provided via Kubernetes secrets management
  # password: <base64-encoded-password>
