apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: r3e-faas
type: Opaque
stringData:
  # These values should be replaced during deployment
  # The actual values should be provided via external secrets management
  # or environment-specific configuration during deployment
  host: "postgres"
  port: "5432"
  username: "postgres"
  password: ""
  database: "r3e_faas"
