apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: r3e-faas
type: Opaque
data:
  # This is a placeholder that should be replaced with a secure password during deployment
  # The value below is base64 encoded and should not be used in production
  password: cG9zdGdyZXMtc2VjcmV0LXBhc3N3b3Jk
