apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: r3e-storage
  namespace: r3e-faas
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocksdb-pvc
  namespace: r3e-faas
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: r3e-storage
  resources:
    requests:
      storage: 50Gi
