# Neo N3 Block Event Handler Configuration

# Function metadata
name: neo-n3-block-handler
description: Example function that processes Neo N3 block events
runtime: javascript
handler: function.js:handler
version: 1.0.0

# Event trigger configuration
trigger:
  type: neo_block
  config:
    # Neo N3 network to monitor (mainnet, testnet, or custom)
    network: testnet
    
    # Optional: RPC node URL (if not using the default for the selected network)
    # rpc_url: https://testnet1.neo.coz.io:443
    
    # Optional: Filter blocks by index range
    # min_index: 1000000
    # max_index: 2000000
    
    # Optional: Process blocks in batches (useful for catching up)
    # batch_size: 10
    
    # Optional: Set to true to process all historical blocks from min_index
    # process_historical: false

# Resource limits
resources:
  memory: 128MB
  timeout: 30s
  
# Environment variables
environment:
  LOG_LEVEL: info
  
# Storage configuration
storage:
  # Enable persistent storage for this function
  enabled: true
  
  # Optional: Storage retention period
  retention_days: 30
