apiVersion: v1
kind: Service
metadata:
  name: {{ include "r3e-faas.fullname" . }}-api
  labels:
    {{- include "r3e-faas.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "r3e-faas.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
