apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "r3e-faas.fullname" . }}-api
  labels:
    {{- include "r3e-faas.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "r3e-faas.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "r3e-faas.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      containers:
      - name: {{ .Chart.Name }}-api
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.api.service.targetPort }}
        env:
        - name: RUST_LOG
          value: {{ .Values.global.logLevel | quote }}
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "r3e-faas.fullname" . }}-config
              key: database_url
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "r3e-faas.fullname" . }}-config
              key: redis_url
        - name: STORAGE_PATH
          value: "/data/rocksdb"
        - name: NEO_RPC_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "r3e-faas.fullname" . }}-config
              key: neo_rpc_url
        - name: ETHEREUM_RPC_URL
          valueFrom:
            configMapKeyRef:
              name: {{ include "r3e-faas.fullname" . }}-config
              key: ethereum_rpc_url
        resources:
          {{- toYaml .Values.api.resources | nindent 10 }}
        volumeMounts:
        - name: rocksdb-storage
          mountPath: /data/rocksdb
        livenessProbe:
          httpGet:
            path: {{ .Values.api.livenessProbe.path }}
            port: {{ .Values.api.service.targetPort }}
          initialDelaySeconds: {{ .Values.api.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.api.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.api.readinessProbe.path }}
            port: {{ .Values.api.service.targetPort }}
          initialDelaySeconds: {{ .Values.api.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.api.readinessProbe.periodSeconds }}
      volumes:
      - name: rocksdb-storage
        persistentVolumeClaim:
          claimName: {{ include "r3e-faas.fullname" . }}-rocksdb-pvc
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
