apiVersion: v1
kind: Secret
metadata:
  name: {{ include "r3e-faas.fullname" . }}-postgres-secret
  labels:
    {{- include "r3e-faas.labels" . | nindent 4 }}
type: Opaque
data:
  # The password should be provided via external secrets management
  # This is a placeholder that will be overridden during installation
  # Using external secrets management is recommended for production deployments
  postgres-password: {{ .Values.postgres.auth.postgresPassword | default (randAlphaNum 16) | b64enc | quote }}
