{{- if .Values.storage.rocksdb.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "r3e-faas.fullname" . }}-rocksdb-pvc
  labels:
    {{- include "r3e-faas.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storage.rocksdb.size }}
{{- end }}
